# This file will contain properties for prod environment
version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=root
      - NODE_ENV=production
    command: node app.js

  # adding new service for mongo DB
  mongo:
    # we don't need to build custom image. we will use pre-defined mongo image from docker hub
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
